apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-api
    rook_cluster: {{ .Values.name }}
  name: rook-api
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: http
    prometheus.io/scrape: "true"
spec:
  clusterIP: 10.254.205.232
  ports:
  - name: metrics
    port: 8124
    protocol: TCP
    targetPort: 8124
  selector:
    app: rook-api
    rook_cluster: {{ .Values.name }}
